spring:
  cloud:
    gateway:
      routes:
        - id: third_party_route
          uri: lb://mail-third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty/?(?<segment>.*),/$\{segment}


        - id: member_route
          uri: lb://mail-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/?(?<segment>.*),/$\{segment}

        - id: ware_route
          uri: lb://mail-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/?(?<segment>.*),/$\{segment}

        - id: product_route
          uri: lb://mail-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/?(?<segment>.*),/$\{segment}


        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/?(?<segment>.*),/renren-fast/$\{segment}


        - id: mail_host_route
          uri: lb://mail-product
          predicates:
            - Host=mymail.com,item.mymail.com

        - id: mail_search_route
          uri: lb://mail-search
          predicates:
            - Host=search.mymail.com


        - id: mail_auth_route
          uri: lb://mail-auth-server
          predicates:
            - Host=auth.mymail.com


    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: mail-gateway
server:
  port: 88


